### ISSUE TITLE
Can't configure multiple wake words

### ISSUE THREAD

**Issue by peltwwb** [uezo/ChatdollKit#294]
I have read the manual and am currently trying out DemoChatGPT, which is working wonderfully. Thank you very much.

However, I’m encountering an issue when attempting to set multiple wake words.

When I set the Wake Word in the Dialog Controller via the Inspector, it works without any issues. 

However, even if I set multiple Wake Words in the OpenAI WakeWordListener as shown in the attached image, they are not recognized.

![image](https://github.com/uezo/ChatdollKit/assets/94046073/96305ef1-7ec8-4595-a8ce-ac5ee97d6ac1)

Additionally, when I configure the wake words in this manner, the Wake Word set in the Dialog Controller also fails to initiate the conversation.

Am I setting the wake words in the correct place?
Are there any additional settings or configurations required to enable multiple wake words?

I would greatly appreciate any advice or guidance on how to set multiple wake words successfully.

**Comment by uezo** [comment]
Hi @peltwwb ,
I guess chat doesn't start because the recognized word by whisper may end with "\n". Set `1` to `Suffix Allowance` to prevent strict evaluation due to an exact match.

This setting allows for minor variations at the end of the recognized word, ensuring that small discrepancies like an additional newline character do not hinder the initiation of the chat.

Additionally, make sure to set the following:

- `Voice` to `Request Type`
- `Normal` to `Intent Priority`

**Comment by peltwwb** [comment]
Thank you! The issue has been resolved!
